In [1]:
import torch

/Users/maxperozek/opt/anaconda3/envs/comp_gr_thy/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import numpy as np

In [3]:
torch.tensor(
    np.random.random((4,4))
)

tensor([[0.5691, 0.9193, 0.5601, 0.6633],
        [0.3982, 0.2160, 0.1316, 0.5877],
        [0.4143, 0.1249, 0.6022, 0.0466],
        [0.4444, 0.0046, 0.7921, 0.6235]], dtype=torch.float64)

In [4]:
torch.rand((4,4))

tensor([[0.2477, 0.0479, 0.0070, 0.5601],
        [0.6260, 0.7455, 0.3795, 0.9411],
        [0.1173, 0.3294, 0.1819, 0.0530],
        [0.3582, 0.0381, 0.6028, 0.3885]])

In [129]:
def f(x):
    return x * x

In [130]:
# initial value is the value in the tensor '1'
current_x = torch.nn.Parameter(torch.tensor(
    [1.0]
))

In [131]:
current_x

Parameter containing:
tensor([1.], requires_grad=True)

In [132]:
# optimizer boilerplate
optimizer = torch.optim.Adam([current_x], 0.001)

In [133]:
value = f(current_x)

In [134]:
value

tensor([1.], grad_fn=<MulBackward0>)

In [135]:
for i in range(1000):
    optimizer.zero_grad() # garbage cleaner from last optimizer step
    value = f(current_x)

    
    value.backward()
    optimizer.step()

In [136]:
current_x

Parameter containing:
tensor([0.2577], requires_grad=True)