In [3]:
import torch

In [4]:
import numpy as np

In [5]:
import matplotlib.pyplot as plt

In [6]:
torch.tensor(
    np.array([.1,.2,.3])
)

tensor([0.1000, 0.2000, 0.3000], dtype=torch.float64)

In [7]:
torch.tensor(
    np.random.random((4,4))
)

tensor([[0.9491, 0.8014, 0.5760, 0.4098],
        [0.4093, 0.1819, 0.4946, 0.1025],
        [0.5025, 0.6777, 0.6995, 0.5120],
        [0.0705, 0.3070, 0.1522, 0.4977]], dtype=torch.float64)

In [8]:
torch.rand((4,4))

tensor([[0.5561, 0.9488, 0.9799, 0.9301],
        [0.5280, 0.1863, 0.4013, 0.1673],
        [0.8524, 0.3105, 0.5140, 0.1172],
        [0.5868, 0.0392, 0.7906, 0.4167]])

In [17]:
def f(x):
    return x * x 

In [12]:
current_x = torch.nn.Parameter(torch.tensor(
    [1.0]
))

In [13]:
current_x

Parameter containing:
tensor([1.], requires_grad=True)

In [14]:
optimizer = torch.optim.Adam([current_x], 0.001)

In [18]:
value = f(current_x)

In [19]:
value

tensor([1.], grad_fn=<MulBackward0>)

In [76]:
for i in range(100):
    optimizer.zero_grad()
    value = f(current_x)
    value.backward()
    optimizer.step()

In [77]:
current_x

Parameter containing:
tensor([0.0067], requires_grad=True)