In [11]:
import numpy as np

In [3]:
# create a np array from python list of lists
my_array = np.array(
    [[1.3,1.1,5,8],
     [9,10,11,13],
     [1e10,3,-1,10]
    ]
)

In [4]:
my_array

array([[ 1.3e+00,  1.1e+00,  5.0e+00,  8.0e+00],
       [ 9.0e+00,  1.0e+01,  1.1e+01,  1.3e+01],
       [ 1.0e+10,  3.0e+00, -1.0e+00,  1.0e+01]])

In [6]:
# (ROWS,COLS)
my_array.shape

(3, 4)

In [8]:
my_array.T.shape

(4, 3)

In [9]:
all_ones = np.ones((3,4))

In [10]:
all_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
my_array + all_ones

array([[2.3e+00, 2.1e+00, 6.0e+00, 9.0e+00],
       [1.0e+01, 1.1e+01, 1.2e+01, 1.4e+01],
       [1.0e+10, 4.0e+00, 0.0e+00, 1.1e+01]])

In [24]:
# wrong shape
my_array.T + all_ones

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [16]:
# matrix multiplication
np.dot(
    my_array.T,
    all_ones
)

array([[1.00e+10, 1.00e+10, 1.00e+10, 1.00e+10],
       [1.41e+01, 1.41e+01, 1.41e+01, 1.41e+01],
       [1.50e+01, 1.50e+01, 1.50e+01, 1.50e+01],
       [3.10e+01, 3.10e+01, 3.10e+01, 3.10e+01]])

In [18]:
np.random.random((3,4))

array([[0.06834162, 0.17358417, 0.00320943, 0.52067884],
       [0.52789171, 0.41268104, 0.05714884, 0.98205681],
       [0.33184316, 0.86440266, 0.18194936, 0.56036696]])

In [19]:
np.random.randint(low=0, high=256, size=(3,4))

array([[ 67,  75, 179, 145],
       [223, 248, 228, 207],
       [136,  46,  95, 253]])

In [23]:
# cast integers as floats
np.random.randint(low=0, high=256, size=(3,4)).astype('float')

array([[186., 151.,  16., 173.],
       [213., 153., 236., 116.],
       [ 12.,  84., 130.,   2.]])

In [26]:
# another way...
(255*np.random.random((3,4))).astype('float')

array([[ 54.29728103, 151.1115731 ,  46.97704106, 104.39448008],
       [ 17.34025574,  55.82221779,   6.59607393, 163.5815688 ],
       [243.78068402, 166.58433765, 227.73763809,  32.31140798]])

In [29]:
print(my_array, '\n\n',np.sin(my_array))

[[ 1.3e+00  1.1e+00  5.0e+00  8.0e+00]
 [ 9.0e+00  1.0e+01  1.1e+01  1.3e+01]
 [ 1.0e+10  3.0e+00 -1.0e+00  1.0e+01]] 

 [[ 0.96355819  0.89120736 -0.95892427  0.98935825]
 [ 0.41211849 -0.54402111 -0.99999021  0.42016704]
 [-0.48750603  0.14112001 -0.84147098 -0.54402111]]


In [32]:
# equivalent of python range()
simple = np.arange(10)

In [33]:
simple

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# inclusive on first index, exclusive on second
simple[3:7]

array([3, 4, 5, 6])

In [37]:
6 % 4 == 2

True

In [39]:
# apply the logical operation to each item in the np array
simple % 4 == 2

array([False, False,  True, False, False, False,  True, False, False,
       False])

In [41]:
# use a boolean 'mask' to index an array
simple[simple % 4 == 2]

array([2, 6])

In [44]:
# index with an array of locations
simple[[1,3,5,7]]

array([1, 3, 5, 7])

In [45]:
simple[[5,3,5,6,8,1,2,3,7]]

array([5, 3, 5, 6, 8, 1, 2, 3, 7])

In [51]:
# broadcasting example
# 1 is a scaler but 1 can be broadcast to a matrix of all ones that is the same dimension as 'simple'
# under the hood, numpy isn't actually creating that array of ones
simple + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
np.random.random((256,256,256,256,256,256,3,256,256,256,256))

ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

In [54]:
# identity matrix
np.eye(32,32)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [56]:
# broadcasting by adding multiple copies of the second matrix
np.eye(32,32) + np.random.random((1,32))

array([[1.95163993, 0.90001514, 0.09603184, ..., 0.88050518, 0.18474138,
        0.26514779],
       [0.95163993, 1.90001514, 0.09603184, ..., 0.88050518, 0.18474138,
        0.26514779],
       [0.95163993, 0.90001514, 1.09603184, ..., 0.88050518, 0.18474138,
        0.26514779],
       ...,
       [0.95163993, 0.90001514, 0.09603184, ..., 1.88050518, 0.18474138,
        0.26514779],
       [0.95163993, 0.90001514, 0.09603184, ..., 0.88050518, 1.18474138,
        0.26514779],
       [0.95163993, 0.90001514, 0.09603184, ..., 0.88050518, 0.18474138,
        1.26514779]])

In [57]:
my_arr = np.random.random((32,32))

In [58]:
my_arr += my_arr.T

In [59]:
np.linalg.eig(my_arr)

(array([31.68817075,  4.08449307, -3.95905785, -3.83902973, -3.74142672,
        -2.89115876,  3.17939331,  3.12521436,  3.01575136,  2.83192131,
        -2.53985672, -2.30713761, -2.15146485,  2.44058095,  2.36377091,
         2.00288036,  1.74353964, -1.77386148, -1.47356553, -1.33186439,
        -1.14278888, -0.87570534, -0.69467302, -0.53410623,  1.23567382,
         1.12450601, -0.12819366,  0.74424891,  0.69526073,  0.50775047,
         0.11989075,  0.24457788]),
 array([[-0.19411229,  0.07940108, -0.11684279, ..., -0.13541045,
          0.06312673,  0.0280154 ],
        [-0.15497893, -0.12665016,  0.09651057, ..., -0.06685677,
         -0.17746102, -0.04655852],
        [-0.16824538,  0.12182823, -0.16203729, ...,  0.09972411,
         -0.19285852, -0.15542367],
        ...,
        [-0.18135366, -0.02011109,  0.20308493, ...,  0.02274667,
         -0.06479025, -0.06067166],
        [-0.17394705, -0.24096031,  0.04171999, ...,  0.13593725,
         -0.11335234, -0.16732673],
   

In [60]:
import scipy